routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.index');
// });

Auth::routes();



Route::get('/', 'Admin\Home\HomeController@index')->name('home');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','Admin\Role\RoleController');
    Route::resource('users','Admin\User\UserController');
    Route::resource('companies','Admin\Company\CompanyController');
    // Route::get('companies/search','Admin\Company\CompanyController');
    Route::resource('categories','Admin\Category\CategoryController');
    Route::resource('products','Admin\Product\ProductController');
    Route::resource('clients','Admin\OrdinaryUser\ClientController');
    Route::resource('suppliers','Admin\OrdinaryUser\SupplierController');
});

app/Http/Controllers/Admin/OrdinaryUser/SupplierController.php
<?php

namespace App\Http\Controllers\Admin\OrdinaryUser;

use App\Models\Company;
use App\Models\OrdinaryUser;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\SuplierRequest;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:supplier-list|supplier-create|supplier-edit|supplier-delete', ['only' => ['index','store']]);
        $this->middleware('permission:supplier-create', ['only' => ['create','store']]);
        $this->middleware('permission:supplier-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:supplier-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $suppliers = OrdinaryUser::whereType('supplier')->paginate(25);

        return view('admin.suppliers.index',['suppliers'=>$suppliers])->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $supplier = new OrdinaryUser();
        $companies = Company::all();
        return view('admin.suppliers.form',['supplier'=>$supplier,'companies'=>$companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SuplierRequest $request)
    {

        $data = $request->validated();
        OrdinaryUser::create($data);
        return redirect()->route('suppliers.index')
                        ->with('success',trans('general.created_Successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $supplier = OrdinaryUser::where('id',$id)->where('type','supplier')->first();
        return view('admin.suppliers.show',['supplier'=>$supplier]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = OrdinaryUser::where('id',$id)->where('type','supplier')->first();
        $companies = Company::all();
        return view('admin.suppliers.form',['supplier'=>$supplier,'companies'=>$companies]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function update(SuplierRequest $request, $id)
    {
        $data = $request->validated();
        $supplier = OrdinaryUser::where('id',$id)->where('type','supplier')->first();
        $supplier->update($data);
        return redirect()->route('suppliers.index')
                        ->with('success',trans('general.updated_Successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = OrdinaryUser::where('id',$id)->where('type','supplier')->first();
        $supplier->delete();
        return redirect()->route('suppliers.index')
                        ->with('success',trans('general.deleted_Successfully'));
    }
}

resources/views/admin/suppliers/form.blade.php
@extends('admin.layouts.app')

@section('header')
    <div class="mb-2 row">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">@lang('general.suppliers')</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left">
                <li class="breadcrumb-item"><a href="{{ route('suppliers.index') }}">@lang('general.suppliers')</a></li>
                <li class="breadcrumb-item active">@if(!$supplier->id) @lang('general.Create_New_supplier') @else @lang('general.update_supplier') @endif</li>
            </ol>
        </div>
    </div>
@endsection

@section('content')


<div class="col-12">
    <div class="card card-info">
        <div class="card-header">
          <h3 class="card-title">@if(!$supplier->id) @lang('general.Create_New_supplier') @else @lang('general.update_supplier') @endif</h3>
        </div>

        @if(!$supplier->id)
            <form class="form-horizontal" method="POST" action="{{ route('suppliers.store') }}">
        @else
            <form class="form-horizontal" method="POST" action="{{ route('suppliers.update',$supplier->id) }}">
            @method('patch')
            <input type="hidden" name="id" value="{{ $supplier->id }}">
        @endif
            @csrf
            <input type="hidden" name="type" value="supplier">
            <div class="card-body">
                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">
                            <div class="col form-group">
                                <label for="name" class="col-sm-4 control-label">@lang('general.name')</label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name" value="{{old('name',$supplier->name)}}" placeholder="@lang('general.name')" required>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col form-group">
                                <label for="phone" class="col-sm-4 control-label">@lang('general.phone')</label>
                                <input type="phone" name="phone" class="form-control @error('phone') is-invalid @enderror" id="phone" value="{{old('phone',$supplier->phone)}}" placeholder="@lang('general.phone')" required>
                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">

                            <div class="col form-group">
                                <label for="user_type" class="col-sm-4 control-label">@lang('general.supplier_type')</label>
                                <select name="user_type" id="user_type" class="form-control">
                                    <option value="">Choose</option>
                                    <option @if($supplier->user_type == 'cash') selected @endif value="cash">cash</option>
                                    <option @if($supplier->user_type == 'installment') selected @endif value="installment">installment</option>
                                    <option @if($supplier->user_type == 'checks') selected @endif value="checks">checks</option>
                                </select>
                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col form-group">
                                <label for="balance" class="col-sm-4 control-label">@lang('general.balance')</label>
                                <input type="text" name="balance" class="form-control @error('balance') is-invalid @enderror" id="balance" value="{{old('balance',$supplier->balance)}}" placeholder="@lang('general.balance')" required>
                                @error('balance')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">
                            <div class="col form-group">
                                <label>@lang('general.companies')</label>
                                <select class="form-control select2" name="company_id">
                                    <option value="">@lang('general.choose')</option>
                                    @foreach($companies as $company)
                                        <option @if($company->id == old('company_id',$supplier->company_id) ) selected @endif value="{{$company->id}}">{{$company->name}}</option>
                                    @endforeach

                                </select>
                                @error('company_id')
                                    <span class="invalid-feedback" style="display:block;" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col form-group">
                                <label for="tax_number" class="col-sm-4 control-label">@lang('general.tax_number')</label>
                                <input type="text" name="tax_number" class="form-control @error('tax_number') is-invalid @enderror" id="tax_number" value="{{old('tax_number',$supplier->tax_number)}}" placeholder="@lang('general.tax_number')" required>
                                @error('tax_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>




                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">
                            <div class="col form-group">
                                <label for="address" class="col-sm-4 control-label">@lang('general.address')</label>
                                <textarea class="form-control @error('address') is-invalid @enderror" name="address" id="address" cols="30" rows="3">{{old('address',$supplier->address)}}</textarea>
                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-info">@lang('general.save')</button>
                <a class="float-left btn btn-danger" href="{{ route('suppliers.index') }}"> @lang('general.back')</a>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/suppliers/index.blade.php
@extends('admin.layouts.app')

@section('header')
    <div class="mb-2 row">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">@lang('general.suppliers')</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('general.dashboard')</a></li>
            <li class="breadcrumb-item active">@lang('general.suppliers')</li>
            </ol>
        </div>
    </div>
@endsection

@section('content')

<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                @can('supplier-create')
                    <a class="btn btn-success" href="{{ route('suppliers.create') }}"><i class="fa fa-plus"></i> @lang('general.Create_New_supplier')</a>
                @endcan
            </h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10%">@lang('general.No')</th>
                        <th>@lang('general.name')</th>
                        <th>@lang('general.address')</th>
                        <th>@lang('general.phone')</th>
                        <th>@lang('general.supplier_type')</th>

                        <th>@lang('general.Action')</th>
                    </tr>
                        @foreach ($suppliers as $key => $supplier)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $supplier->name }}</td>
                            <td>@if(!is_null($supplier->address)){{ $supplier->address }}@else @lang('general.no_data_found')@endif</td>
                            <td>{{ $supplier->phone }}</td>
                            <td>{{ $supplier->user_type }}</td>
                            <td>
                                <form class="delete-form" action="{{ route('suppliers.destroy',$supplier->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <a class="btn btn-info btn-sm" href="{{ route('suppliers.show',$supplier->id) }}"><i class="fa fa-eye fa-sm"></i> @lang('general.Show')</a>
                                    @can('supplier-edit')
                                        <a class="btn btn-primary btn-sm" href="{{ route('suppliers.edit',$supplier->id) }}"><i class="fa fa-edit fa-sm"></i> @lang('general.Edit')</a>
                                    @endcan
                                    @can('supplier-delete')
                                        <button type="button" class="btn btn-danger btn-sm" onclick="confirmDelete('delete-form')"><i class="fa fa-trash fa-sm"></i> @lang('general.Delete')</button>
                                    @endcan
                                </form>
                            </td>
                        </tr>
                       @endforeach
                </tbody>
            </table>
        </div>
        <div class="clearfix card-footer">
            {{ $suppliers->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/suppliers/show.blade.php
@extends('admin.layouts.app')

@section('header')
<div class="mb-2 row">
    <div class="col-sm-6">
      <h1 class="m-0 text-dark">@lang('general.dashboard')</h1>
    </div>{{-- /.col --}}
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a href="{{route('suppliers.index')}}">@lang('general.suppliers')</a></li>
        <li class="breadcrumb-item active">{{$supplier->name}}</li>
      </ol>
    </div>{{-- /.col --}}
  </div>{{-- /.row --}}
@endsection
@section('content')
<div class="col-12">

    <div class="card card-outline card-primary">
        <div class="card-header">
          <h3 class="card-title">@lang('general.supplier')</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
          {{-- /.card-tools --}}
        </div>
        {{-- /.card-header --}}

            <div class="card-body">
                <div class="row">


                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.name')</h5>
                        <span class="description-text">{{$supplier->name}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.email')</h5>
                        <span class="description-text">{{$supplier->email}}</span>
                        </div>

                    </div>

                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.job')</h5>
                        <span class="description-text">{{$supplier->job}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.hire_date')</h5>
                        <span class="description-text">{{$supplier->hire_date}}</span>
                        </div>

                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.address')</h5>
                        <span class="description-text">{{$supplier->address}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.phone')</h5>
                        <span class="description-text">{{$supplier->phone}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.salary')</h5>
                        {{-- <span class="description-text">{{$supplier->salary}}</span> --}}
                        </div>

                    </div>
                </div>
                <hr>

            </div>

        {{-- /.card-body --}}
    </div>

</div>

@endsection