routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.index');
// });

Auth::routes();



Route::get('/', 'Admin\Home\HomeController@index')->name('home');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','Admin\Role\RoleController');
    Route::resource('users','Admin\User\UserController');
    Route::resource('companies','Admin\Company\CompanyController');
    // Route::get('companies/search','Admin\Company\CompanyController');
    Route::resource('categories','Admin\Category\CategoryController');
    Route::resource('products','Admin\Product\ProductController');
    Route::resource('clients','Admin\OrdinaryUser\ClientController');
    Route::resource('suppliers','Admin\OrdinaryUser\SupplierController');
});

app/Http/Controllers/Admin/OrdinaryUser/ClientController.php
<?php

namespace App\Http\Controllers\Admin\OrdinaryUser;

use App\Models\OrdinaryUser;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ClientRequest;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:client-list|client-create|client-edit|client-delete', ['only' => ['index','store']]);
        $this->middleware('permission:client-create', ['only' => ['create','store']]);
        $this->middleware('permission:client-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:client-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $clients = OrdinaryUser::whereType('client')->paginate(25);
        return view('admin.clients.index',['clients'=>$clients])->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $client = new OrdinaryUser();
        return view('admin.clients.form',['client'=>$client]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClientRequest $request)
    {
        $data = $request->validated();
        OrdinaryUser::create($data);
        return redirect()->route('clients.index')
                        ->with('success',trans('general.created_Successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = OrdinaryUser::where('id',$id)->where('type','client')->first();
        return view('admin.clients.show',['client'=>$client]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = OrdinaryUser::where('id',$id)->where('type','client')->first();
        return view('admin.clients.form',['client'=>$client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function update(ClientRequest $request, $id)
    {
        $data = $request->validated();
        $client = OrdinaryUser::where('id',$id)->where('type','client')->first();
        $client->update($data);
        return redirect()->route('clients.index')
                        ->with('success',trans('general.updated_Successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\OrdinaryUser  $ordinaryUser
     * @return \Illuminate\Http\Response
     */
    public function destroy(OrdinaryUser $ordinaryUser)
    {
        $client = OrdinaryUser::where('id',$id)->where('type','client')->first();
        $client->delete();
        return redirect()->route('clients.index')
                        ->with('success',trans('general.deleted_Successfully'));
    }
}

resources/views/admin/clients/form.blade.php
@extends('admin.layouts.app')

@section('header')
    <div class="mb-2 row">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">@lang('general.clients')</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left">
                <li class="breadcrumb-item"><a href="{{ route('clients.index') }}">@lang('general.clients')</a></li>
                <li class="breadcrumb-item active">@if(!$client->id) @lang('general.Create_New_client') @else @lang('general.update_client') @endif</li>
            </ol>
        </div>
    </div>
@endsection

@section('content')


<div class="col-12">
    <div class="card card-info">
        <div class="card-header">
          <h3 class="card-title">@if(!$client->id) @lang('general.Create_New_client') @else @lang('general.update_client') @endif</h3>
        </div>

        @if(!$client->id)
            <form class="form-horizontal" method="POST" action="{{ route('clients.store') }}">
        @else
            <form class="form-horizontal" method="POST" action="{{ route('clients.update',$client->id) }}">
            @method('patch')
            <input type="hidden" name="id" value="{{ $client->id }}">
        @endif
            @csrf
            <input type="hidden" name="type" value="client">
            <div class="card-body">
                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">
                            <div class="col form-group">
                                <label for="name" class="col-sm-4 control-label">@lang('general.name')</label>
                                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name" value="{{old('name',$client->name)}}" placeholder="@lang('general.name')" required>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col form-group">
                                <label for="phone" class="col-sm-4 control-label">@lang('general.phone')</label>
                                <input type="phone" name="phone" class="form-control @error('phone') is-invalid @enderror" id="phone" value="{{old('phone',$client->phone)}}" placeholder="@lang('general.phone')" required>
                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">

                            <div class="col form-group">
                                <label for="user_type" class="col-sm-4 control-label">@lang('general.client_type')</label>
                                <select name="user_type" id="user_type" class="form-control">
                                    <option value="">Choose</option>
                                    <option @if($client->user_type == 'cash') selected @endif value="cash">cash</option>
                                    <option @if($client->user_type == 'installment') selected @endif value="installment">installment</option>
                                    <option @if($client->user_type == 'checks') selected @endif value="checks">checks</option>
                                </select>
                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="col form-group">
                                <label for="balance" class="col-sm-4 control-label">@lang('general.balance')</label>
                                <input type="text" name="balance" class="form-control @error('balance') is-invalid @enderror" id="balance" value="{{old('balance',$client->balance)}}" placeholder="@lang('general.balance')" required>
                                @error('balance')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">

                            <div class="col form-group">
                                <label for="address" class="col-sm-4 control-label">@lang('general.address')</label>
                                <textarea class="form-control @error('address') is-invalid @enderror" name="address" id="address" cols="30" rows="3">{{old('address',$client->address)}}</textarea>
                                @error('address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                        </div>
                    </div>


            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-info">@lang('general.save')</button>
                <a class="float-left btn btn-danger" href="{{ route('clients.index') }}"> @lang('general.back')</a>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/clients/index.blade.php
@extends('admin.layouts.app')

@section('header')
    <div class="mb-2 row">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">@lang('general.clients')</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('general.dashboard')</a></li>
            <li class="breadcrumb-item active">@lang('general.clients')</li>
            </ol>
        </div>
    </div>
@endsection

@section('content')

<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                @can('client-create')
                    <a class="btn btn-success" href="{{ route('clients.create') }}"><i class="fa fa-plus"></i> @lang('general.Create_New_client')</a>
                @endcan
            </h3>
        </div>

        <div class="card-body">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <th style="width: 10%">@lang('general.No')</th>
                        <th>@lang('general.name')</th>
                        <th>@lang('general.address')</th>
                        <th>@lang('general.phone')</th>
                        <th>@lang('general.client_type')</th>

                        <th>@lang('general.Action')</th>
                    </tr>
                        @foreach ($clients as $key => $client)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $client->name }}</td>
                            <td>@if(!is_null($client->address)){{ $client->address }}@else @lang('general.no_data_found')@endif</td>
                            <td>{{ $client->phone }}</td>
                            <td>{{ $client->user_type }}</td>
                            <td>
                                <form class="delete-form" action="{{ route('clients.destroy',$client->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <a class="btn btn-info btn-sm" href="{{ route('clients.show',$client->id) }}"><i class="fa fa-eye fa-sm"></i> @lang('general.Show')</a>
                                    @can('client-edit')
                                        <a class="btn btn-primary btn-sm" href="{{ route('clients.edit',$client->id) }}"><i class="fa fa-edit fa-sm"></i> @lang('general.Edit')</a>
                                    @endcan
                                    @can('client-delete')
                                        <button type="button" class="btn btn-danger btn-sm" onclick="confirmDelete('delete-form')"><i class="fa fa-trash fa-sm"></i> @lang('general.Delete')</button>
                                    @endcan
                                </form>
                            </td>
                        </tr>
                       @endforeach
                </tbody>
            </table>
        </div>
        <div class="clearfix card-footer">
            {{ $clients->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/clients/show.blade.php
@extends('admin.layouts.app')

@section('header')
<div class="mb-2 row">
    <div class="col-sm-6">
      <h1 class="m-0 text-dark">@lang('general.dashboard')</h1>
    </div>{{-- /.col --}}
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a href="{{route('clients.index')}}">@lang('general.clients')</a></li>
        <li class="breadcrumb-item active">{{$client->name}}</li>
      </ol>
    </div>{{-- /.col --}}
  </div>{{-- /.row --}}
@endsection
@section('content')
<div class="col-12">

    <div class="card card-outline card-primary">
        <div class="card-header">
          <h3 class="card-title">@lang('general.client')</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
          {{-- /.card-tools --}}
        </div>
        {{-- /.card-header --}}

            <div class="card-body">
                <div class="row">


                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.name')</h5>
                        <span class="description-text">{{$client->name}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.email')</h5>
                        <span class="description-text">{{$client->email}}</span>
                        </div>

                    </div>

                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.job')</h5>
                        <span class="description-text">{{$client->job}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.hire_date')</h5>
                        <span class="description-text">{{$client->hire_date}}</span>
                        </div>

                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-6 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.address')</h5>
                        <span class="description-text">{{$client->address}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.phone')</h5>
                        <span class="description-text">{{$client->phone}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.salary')</h5>
                        {{-- <span class="description-text">{{$client->salary}}</span> --}}
                        </div>

                    </div>
                </div>
                <hr>

            </div>

        {{-- /.card-body --}}
    </div>

</div>

@endsection