routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.index');
// });

Auth::routes();



Route::get('/', 'Admin\Home\HomeController@index')->name('home');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','Admin\Role\RoleController');
    Route::resource('users','Admin\User\UserController');
    Route::resource('companies','Admin\Company\CompanyController');
    // Route::get('companies/search','Admin\Company\CompanyController');
    Route::resource('categories','Admin\Category\CategoryController');
    Route::resource('products','Admin\Product\ProductController');
    Route::resource('clients','Admin\OrdinaryUser\ClientController');
    Route::resource('suppliers','Admin\OrdinaryUser\SupplierController');
});

resources/views/admin/layouts/_footer.blade.php
{{-- /.content-wrapper --}}
<footer class="main-footer">
  <strong>CopyLeft &copy; 2018
</footer>

{{-- Control Sidebar --}}
<aside class="control-sidebar control-sidebar-dark">
  {{-- Control sidebar content goes here --}}
</aside>
{{-- /.control-sidebar --}}
</div>
{{-- ./wrapper --}}

{{-- jQuery --}}
<script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>
{{-- jQuery UI 1.11.4 --}}
<script src="{{asset('admin/dist/js/jquery-ui.min.js')}}"></script>
{{-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip --}}
<script>
$.widget.bridge('uibutton', $.ui.button)
</script>
{{-- Bootstrap 4 --}}
<script src="{{asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
{{-- Morris.js charts --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{{asset('admin/dist/js/raphael-min.js')}}"></script>
<script src="{{asset('admin/plugins/morris/morris.min.js')}}"></script>
{{-- Sparkline --}}
<script src="{{asset('admin/plugins/sparkline/jquery.sparkline.min.js')}}"></script>
{{-- jvectormap --}}
<script src="{{asset('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
{{-- jQuery Knob Chart --}}
<script src="{{asset('admin/plugins/knob/jquery.knob.js')}}"></script>
{{-- daterangepicker --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
<script src="{{asset('admin/plugins/daterangepicker/daterangepicker.js')}}"></script>
{{-- datepicker --}}
<script src="{{asset('admin/plugins/datepicker/bootstrap-datepicker.js')}}"></script>
{{-- Bootstrap WYSIHTML5 --}}
<script src="{{asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
{{-- Slimscroll --}}
<script src="{{asset('admin/plugins/slimScroll/jquery.slimscroll.min.js')}}"></script>

<!-- SweetAlert2 -->
<script src="{{asset('admin/plugins/sweetalert2/sweetalert2.min.js')}}"></script>
<!-- Toastr -->
<script src="{{asset('admin/plugins/toastr/toastr.min.js')}}"></script>
{{-- FastClick --}}
<script src="{{asset('admin/plugins/daterangepicker/daterangepicker.js')}}"></script>
{{-- AdminLTE App --}}
<script src="{{asset('admin/dist/js/adminlte.js')}}"></script>
{{-- AdminLTE dashboard demo (This is only for demo purposes) --}}
{{--  <script src="{{asset('admin/dist/js/pages/dashboard.js')}}"></script>  --}}
{{-- AdminLTE for demo purposes --}}
<script src="{{asset('admin/dist/js/demo.js')}}"></script>
<script src="{{asset('admin/dist/js/sweetalert.min.js')}}"></script>

<script>
    function confirmDelete(item_id) {
        swal({
            title: "{{ __('general.Are_you_sure') }}",
            text: "{{ __('general.Once_deleted') }}",
            icon: "warning",
            buttons: ["{{ __('general.no') }}", "{{ __('general.Delete') }}"],
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $('.'+item_id).submit();
                } else {
                    swal("{{ __('general.Cancelled_Successfully') }}");
                }
            });
    }
</script>
    @yield('js')
</body>
</html>

resources/views/admin/layouts/_header.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>نظام المخازن</title>
  {{-- Tell the browser to be responsive to screen width --}}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {{-- Font Awesome --}}
  <link rel="stylesheet" href="{{asset('admin/plugins/font-awesome/css/font-awesome.min.css')}}">
  {{-- Ionicons --}}
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  {{-- Theme style --}}
  <link rel="stylesheet" href="{{asset('admin/dist/css/adminlte.min.css')}}">
  {{-- iCheck --}}
  <link rel="stylesheet" href="{{asset('admin/plugins/iCheck/flat/blue.css')}}">
  {{-- Morris chart --}}
  <link rel="stylesheet" href="{{asset('admin/plugins/morris/morris.css')}}">
  {{-- jvectormap --}}
  <link rel="stylesheet" href="{{asset('admin/plugins/jvectormap/jquery-jvectormap-1.2.2.css')}}">
  {{-- Date Picker --}}
  <link rel="stylesheet" href="{{asset('admin/plugins/datepicker/datepicker3.css')}}">
  {{-- Daterange picker --}}
  <link rel="stylesheet" href="{{asset('admin/plugins/daterangepicker/daterangepicker-bs3.css')}}">
  {{-- bootstrap wysihtml5 - text editor --}}
  <link rel="stylesheet" href="{{asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">
  <!-- SweetAlert2 -->
  <link rel="stylesheet" href="{{asset('admin/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{{asset('admin/plugins/toastr/toastr.min.css')}}">
  {{-- Google Font: Source Sans Pro --}}

  <link href="https://fonts.googleapis.com/css?family=Tajawal&display=swap" rel="stylesheet">
  {{-- bootstrap rtl --}}
  <link rel="stylesheet" href="{{asset('admin/dist/css/bootstrap-rtl.min.css')}}">
  {{-- template rtl version --}}
  <link rel="stylesheet" href="{{asset('admin/dist/css/custom-style.css')}}">
  <style>
      body{
        font-family: 'Tajawal', sans-serif !important;
      }

  </style>
  <script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>

</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

resources/views/admin/layouts/_messages.blade.php
@if(session('success'))


<script type="text/javascript">
    $(function() {
      const Toast = Swal.mixin({
        toast: true,
        position: 'mid-center',
        showConfirmButton: false,
        timer: 1500
      });


      toastr.success("{{ session('success') }}")

    });

  </script>

@endif


@if(session('error'))


<script type="text/javascript">
    $(function() {
      const Toast = Swal.mixin({
        toast: true,
        position: 'mid-center',
        showConfirmButton: false,
        timer: 1500
      });


      toastr.error("{{ session('error') }}")

    });

  </script>


@endif

resources/views/admin/layouts/_nav.blade.php
<nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
    {{-- Left navbar links --}}
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
      </li>
    </ul>

    
 

    {{-- Right navbar links --}}
    <ul class="navbar-nav mr-auto">
      {{-- Messages Dropdown Menu --}}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-comments-o"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left">
          <a href="#" class="dropdown-item">
            {{-- Message Start --}}
            @if(Auth::check())
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 ml-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                   {{auth()->user()->name}}
                  <span class="float-left text-sm text-danger"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">با من تماس بگیر لطفا...</p>
                <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 ساعت قبل</p>
              </div>
            </div>
            @endif
            {{-- Message End --}}
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            {{-- Message Start --}}
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle ml-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  پیمان احمدی
                  <span class="float-left text-sm text-muted"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">من پیامتو دریافت کردم</p>
                <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 ساعت قبل</p>
              </div>
            </div>
            {{-- Message End --}}
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            {{-- Message Start --}}
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle ml-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  سارا وکیلی
                  <span class="float-left text-sm text-warning"><i class="fa fa-star"></i></span>
                </h3>
                <p class="text-sm">پروژه اتون عالی بود مرسی واقعا</p>
                <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i>4 ساعت قبل</p>
              </div>
            </div>
            {{-- Message End --}}
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">مشاهده همه پیام‌ها</a>
        </div>
      </li>
      {{-- Notifications Dropdown Menu --}}
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-bell-o"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left">
          <span class="dropdown-item dropdown-header">15 نوتیفیکیشن</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-envelope ml-2"></i> 4 پیام جدید
            <span class="float-left text-muted text-sm">3 دقیقه</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-users ml-2"></i> 8 درخواست دوستی
            <span class="float-left text-muted text-sm">12 ساعت</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fa fa-file ml-2"></i> 3 گزارش جدید
            <span class="float-left text-muted text-sm">2 روز</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">مشاهده همه نوتیفیکیشن</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
                class="fa fa-th-large"></i></a>
      </li>
    </ul>
  </nav>

resources/views/admin/layouts/_sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    {{-- Brand Logo --}}
    <a href="#" class="brand-link">
      {{--  <img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">  --}}
      <span class="brand-text font-weight-light">نظام المخازن</span>
    </a>

    {{-- Sidebar --}}
    <div class="sidebar" style="direction: ltr">
      <div style="direction: rtl">
        {{-- Sidebar user panel (optional) --}}

        @if(Auth::check())
            <div class="pb-3 mt-3 mb-3 user-panel d-flex">
                <div class="image">
                    <img src="https://secure.gravatar.com/avatar/5ffa2a1ffeb767c60ab7e1052e385d5c?s=52&d=mm&r=g" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">{{auth()->user()->name}}</a>
                </div>
            </div>
        @endif
        {{-- Sidebar Menu --}}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
             {{--  main pages  --}}
                <li class="nav-item has-treeview @if(request()->is('roles')) menu-open @endif">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-home"></i>
                        <p>
                            الرئيسية
                        <i class="right fa fa-angle-left"></i>
                        </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="fa fa-pie-chart nav-icon"></i>
                            <p>الاحصائيات</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="pages/charts/flot.html" class="nav-link">
                            <i class="fa fa-circle-o nav-icon"></i>
                            <p>الإعدادات</p>
                        </a>
                    </li>
                    @can('role-list')
                        <li class="nav-item">
                            <a href="{{ route('roles.index') }}" class="nav-link @if(request()->is('roles')) active @endif">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>الصلاحيات</p>
                            </a>
                        </li>
                    @endcan
                </ul>
                </li>
                {{--  !main pages  --}}
                {{--  users link  --}}
                @can('user-list')
                    <li class="nav-item">
                        <a href="{{ route('users.index') }}" class="nav-link @if(request()->is('users')) active @endif">
                            <i class="nav-icon fa fa-users"></i>
                            <p>
                                @lang('general.users')
                            </p>
                        </a>
                    </li>
                @endcan
                {{--  ! users link  --}}
                {{--  clients link  --}}
                @can('client-list')
                    <li class="nav-item">
                        <a href="{{ route('clients.index') }}" class="nav-link @if(request()->is('clients')) active @endif">
                            <i class="nav-icon fa fa-users"></i>
                            <p>
                                @lang('general.clients')
                            </p>
                        </a>
                    </li>
                @endcan
                {{--  ! clients link  --}}
                {{--  suppliers link  --}}
                @can('supplier-list')
                    <li class="nav-item">
                        <a href="{{ route('suppliers.index') }}" class="nav-link @if(request()->is('suppliers')) active @endif">
                            <i class="nav-icon fa fa-users"></i>
                            <p>
                                @lang('general.suppliers')
                            </p>
                        </a>
                    </li>
                @endcan
                {{--  ! suppliers link  --}}
                {{--  companies link  --}}
                @can('company-list')
                    <li class="nav-item">
                        <a href="{{ route('companies.index') }}" class="nav-link @if(request()->is('companies')) active @endif">
                            <i class="nav-icon fa fa-building"></i>
                            <p>
                                @lang('general.companies')
                            </p>
                        </a>
                    </li>
                @endcan
                {{--  ! companies link  --}}
                {{--  categories link  --}}
                @can('category-list')
                    <li class="nav-item">
                        <a href="{{ route('categories.index') }}" class="nav-link @if(request()->is('categories')) active @endif">
                            <i class="nav-icon fa fa-th"></i>
                            <p>
                                @lang('general.categories')
                            </p>
                        </a>
                    </li>
                @endcan
                {{--  ! categories link  --}}
                {{--  products link  --}}
                @can('product-list')
                    <li class="nav-item">
                        <a href="{{ route('products.index') }}" class="nav-link @if(request()->is('products')) active @endif">
                            <i class="nav-icon fa fa-product-hunt"></i>
                            <p>
                                @lang('general.products')
                            </p>
                        </a>
                    </li>
                @endcan
                {{--  ! products link  --}}
                {{--  logout link  --}}
                <li class="nav-item">
                    <a href="{{ route('logout') }}" class="nav-link" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="nav-icon fa fa-sign-out"></i>
                        <p>@lang('general.Logout')</p>

                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
                {{--  !users link  --}}
            </ul>
        </nav>
        {{-- /.sidebar-menu --}}
      </div>
    </div>
    {{-- /.sidebar --}}
</aside>

resources/views/admin/layouts/app.blade.php
{{--  header  --}}
 @include('admin.layouts._header')
  {{-- Navbar --}}
  @include('admin.layouts._nav')
  {{-- /.navbar --}}

  {{-- Main Sidebar Container --}}

  @include('admin.layouts._sidebar')
  {{-- Main Sidebar Container --}}

  {{-- Content Wrapper. Contains page content --}}
  <div class="content-wrapper">
    {{-- Content Header (Page header) --}}
    <section class="content-header">
        <div class="content-header">
            <div class="container-fluid">
                @yield('header')
            </div><!-- /.container-fluid -->
          </div>



    </section>
    {{-- /.content-header --}}

    {{-- Main content --}}
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          @include('admin.layouts._messages')
        @yield('content')

        </div>  {{-- /.row (main row) --}}
      </div>{{-- /.container-fluid --}}

    </section>
    {{-- /.content --}}
  </div>
  {{--  footer  --}}
  @include('admin.layouts._footer')


  @yield('js')

resources/views/admin/layouts/errors.blade.php
@if(count($errors))
    <div class="form-group">
        <div class = "alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    </div>
@endif