routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.index');
// });

Auth::routes();



Route::get('/', 'Admin\Home\HomeController@index')->name('home');


Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','Admin\Role\RoleController');
    Route::resource('users','Admin\User\UserController');
    Route::resource('companies','Admin\Company\CompanyController');
    // Route::get('companies/search','Admin\Company\CompanyController');
    Route::resource('categories','Admin\Category\CategoryController');
    Route::resource('products','Admin\Product\ProductController');
    Route::resource('clients','Admin\OrdinaryUser\ClientController');
    Route::resource('suppliers','Admin\OrdinaryUser\SupplierController');
});

app/Models/Category.php
<?php

namespace App\Models;


use App\Models\Product;
class Category extends Model
{
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Category;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:category-list|category-create|category-edit|category-delete', ['only' => ['index','store']]);
        $this->middleware('permission:category-create', ['only' => ['create','store']]);
        $this->middleware('permission:category-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:category-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->paginate(20);
        return view('admin.basic_information.categories.index',['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $data = $request->validated();
        Category::create($data);
        return redirect()->route('categories.index')
                        ->with('success',trans('general.created_Successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.basic_information.categories.show',compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $data = $request->validated();
        $category->update($data);
        return redirect()->route('categories.index')
                        ->with('success',trans('general.updated_Successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if(count($category->products) > 0)
        {
            $category->products()->delete();
        }
        $category->delete();
        return redirect()->route('categories.index')
                        ->with('success',trans('general.deleted_Successfully'));
    }
}

resources/views/admin/basic_information/categories/form.blade.php
{{-- Modal --}}
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
		  <div class="modal-content">
			<div class="modal-header">

                <h5 class="modal-title" id="exampleModalLongTitle"><i class="fa fa-plus-circle"></i> @lang('general.Create_New_category')</h5>

			</div>
			<div class="modal-body">

                <form action="{{route('categories.store')}}" method="post" enctype="multipart/form-data">

                {{csrf_field()}}

                <div class="row">
                    <div class="col-12">
                        <div class="mt-4 d-flex justify-content-between">

                            <div class="col form-group">
                                <label>@lang('general.category_code')</label>
                                <input type="text" class="form-control"
                                       name="code" value="{{old('code')}}"
                                       placeholder="@lang('general.category_code')">
                                @if($errors->has('code'))
                                <div class="invalid-feedback" style="display:block;">
                                {{ $errors->first('code') }}
                                </div>
                                @endif
                            </div>


                        </div>
                        <div class="mt-4 d-flex justify-content-between">

                            <div class="col form-group">
                                <label>@lang('general.name')</label>
                                <input type="text" class="form-control"
                                       name="name"
                                       value="{{old('name')}}"
                                       placeholder="@lang('general.name')">
                                @if($errors->has('name'))
                                <div class="invalid-feedback" style="display:block;">
                                {{ $errors->first('name') }}
                                </div>
                                @endif
                            </div>

                        </div>
                    </div>



                </div>

			</div>
			<div class="modal-footer">
                <button type="button" class="ml-2 btn btn-danger close-companymodal" data-dismiss="modal">Close</button>

                <button type="submit" class="btn btn-success btn-l btn-rounded"> <i class="fa fa-check"></i> @lang('general.save')</button>

            </div>
        </form>
		  </div>
		</div>
</div>

resources/views/admin/basic_information/categories/index.blade.php
@extends('admin.layouts.app')

@section('header')
    <div class="mb-2 row">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">@lang('general.categories')</h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-left">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('general.dashboard')</a></li>
            <li class="breadcrumb-item active">@lang('general.categories')</li>
            </ol>
        </div>
    </div>
@endsection

@section('content')

    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    @can('category-create')
                    <button type="button" class="btn btn-success add" data-toggle="modal" data-target="#exampleModalCenter">
                        <i class="fa fa-plus-circle"></i> @lang('general.Create_New_category')
					</button>
                    @endcan
                </h3>
            </div>

            <div class="card-body">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 10%">@lang('general.No')</th>
							<th>@lang('general.category_code')</th>
                            <th>@lang('general.name')</th>
							<th>@lang('general.created_at')</th>
                            <th>@lang('general.Action')</th>
                            </tr>
                        @foreach($categories as $category)
                            <tr>
                                <td>{{$category->id}}</td>
                                <td>{{$category->code}}</td>
                                <td>{{$category->name}}</td>
                                <td>{{$category->created_at->format('Y/m/d')}}</td>
                                <td>
                                    <form class="delete-form" action="{{ route('categories.destroy',$category->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <a class="btn btn-info btn-sm" href="{{ route('categories.show',$category->id) }}"><i class="fa fa-eye fa-sm"></i> @lang('general.Show')</a>
                                        @can('category-edit')
                                        <span data-toggle="modal" data-target="#exampleModalCenter">
                                            <a data-url="{{route('categories.update',$category->id)}}"
                                                                       data-code="{{$category->code}}" data-name="{{$category->name}}"
                                            href="{{route('categories.edit',$category->id)}}" class="btn btn-primary btn-sm edit"
                                                data-toggle="tooltip" data-placement="top" title="@lang('general.Edit')">
                                                <i class="fa fa-edit fa-sm"></i> @lang('general.Edit')
                                            </a>
                                        </span>
                                        @endcan
                                        @can('category-delete')
                                            <button type="button" class="btn btn-danger btn-sm" onclick="confirmDelete('delete-form')"><i class="fa fa-trash fa-sm"></i> @lang('general.Delete')</button>
                                        @endcan
                                    </form>
                                </td>
                            </tr>
                        @endforeach



                    </tbody>
                </table>
            </div>


        </div>
        {!! $categories->render() !!}
    </div>
    @include('admin.basic_information.categories.form')
    <button type="button" class="btn btn-primary display-error" data-toggle="modal" data-target="#exampleModalCenter" style="display:none;"></button>


    {{--  search  --}}
    @include('admin.basic_information.categories.search')
    @endsection

@section('js')
<script>
    $('.add').click(function(){
    $('#exampleModalLongTitle').text("@lang('general.Create_New_category')");
    $('.modal-body form').attr('action', "{{route('categories.store')}}");
    $('.modal-body form').find('input[name!="_token"]').val('');
    $('.modal-body form').find('input[name="_method"]').remove();
    localStorage.setItem("action", "create");
    localStorage.setItem("prev_url", "{{route('categories.store')}}");

    });

    // show edit data of company
    $('.edit').click(function(e){
         e.preventDefault();
         $('input[name="code"]').val($(this).data('code'));
         $('input[name="name"]').val($(this).data('name'));
         $('#exampleModalLongTitle').text("@lang('general.update')");
         $('.modal-body form').attr('action',$(this).data('url'));
         localStorage.setItem("prev_url", $(this).data('url'));
         $('.modal-body form').append('@method("PUT")');
         localStorage.setItem("action", "update");
    });

    //diplay errors to user
    @if($errors->any())

         if(localStorage.getItem("action") == 'update'){
            $('.modal-body form').append('@method("PUT")');
            $('#exampleModalLongTitle').text("@lang('general.update')");
          }

            $('.display-error').click();
            $('.modal-body form').attr('action',localStorage.getItem("prev_url"));

    @endif

    $('#exampleModalCenter').on('hidden.bs.modal', function () {
        $('.modal-body form').find('.invalid-feedback,input[name="_method"]').remove();
    })
</script>
@endsection

resources/views/admin/basic_information/categories/search.blade.php
{{-- Modal --}}
<div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">

            <h5 class="modal-title" id="exampleModalLongTitle"><i class="fa fa-search"></i> @lang('admin.search')</h5>

        </div>
        <div class="modal-body">

            <form action="#" method="get">



            <div class="row">
                <div class="col-12">
                    <div class="mt-4 d-flex justify-content-between">

                        <div class="col form-group">
                            <label>@lang('admin.company_code')</label>
                            <input type="text" class="form-control"
                                   name="code" value="{{old('code')}}"
                                   placeholder="@lang('admin.company_code')">
                        </div>


                    </div>
                    <div class="mt-4 d-flex justify-content-between">

                        <div class="col form-group">
                            <label>@lang('admin.name')</label>
                            <input type="text" class="form-control"
                                   name="name"
                                   value="{{old('name')}}"
                                   placeholder="@lang('admin.name')">

                        </div>

                    </div>
                </div>


                <div class="text-center col-md-12">
                    <button type="submit" class="mt-2 mb-3 btn btn-primary btn-l btn-rounded"> <i class="fa fa-check"></i> @lang('admin.search')</button>
                    </div>
            </div>
        </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-companymodal" data-dismiss="modal">Close</button>

        </div>
      </div>
    </div>
</div>

resources/views/admin/basic_information/categories/show.blade.php
@extends('admin.layouts.app')

@section('header')
<div class="mb-2 row">
    <div class="col-sm-6">
      <h1 class="m-0 text-dark">@lang('general.dashboard')</h1>
    </div>{{-- /.col --}}
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a href="{{route('categories.index')}}">@lang('general.categories')</a></li>
        <li class="breadcrumb-item active">{{$category->name}}</li>
      </ol>
    </div>{{-- /.col --}}
  </div>{{-- /.row --}}
@endsection
@section('content')
<div class="col-12">

    <div class="card card-outline card-primary">
        <div class="card-header">
          <h3 class="card-title">@lang('general.category_data')</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
          {{-- /.card-tools --}}
        </div>
        {{-- /.card-header --}}

            <div class="card-body">
                <div class="row">


                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.category_name')</h5>
                        <span class="description-text">{{$category->name}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.category_code')</h5>
                        <span class="description-text">{{$category->code}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.created_at')</h5>
                        <span class="description-text">{{$category->created_at->format('Y/m/d')}}</span>
                        </div>

                    </div>
                    <div class="col-sm-3 border-right">
                        <div class="description-block">
                        <h5 class="description-header">@lang('general.updated_at')</h5>
                        <span class="description-text">{{$category->updated_at->format('Y/m/d')}}</span>
                        </div>

                    </div>
                </div>



            </div>

        {{-- /.card-body --}}
    </div>
    @if(isset($category->products) && !is_null($category->products))
    <div class="card card-outline card-success">
        <div class="card-header">
          <h3 class="card-title">@lang('general.products')</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
          {{-- /.card-tools --}}
        </div>
        {{-- /.card-header --}}

            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>@lang('general.No')</th>
                            <th>@lang('general.product_code')</th>
                            <th>@lang('general.name')</th>
                            <th>@lang('general.purchase_price')</th>

                            <th>@lang('general.controll')</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($category->products as $product)
                        <tr>
                            <th scope="row">{{$product->id}}</th>
                            <td>{{$product->code}}</td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->purchase_price}}</td>
                            <td>

                                <a href="{{ route('products.show', $product->id) }}" class="btn btn-info btn-sm" data-target='tooltip' title="{{ trans('general.show') }}"><i class="fa fa-eye fa-sm"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        {{-- /.card-body --}}
    </div>
    @else
    <div class="card card-outline card-danger">
        <div class="card-header">
          <h3 class="card-title">@lang('general.products')</h3>
        </div>
        <div class="card-body">
            @lang('general.no_data_found')
        </div>
        <!-- /.card-body -->
      </div>

    @endif
</div>

@endsection